site_name: Get Cohorts
theme:
    name: material

markdown_extensions:
    - mkautodoc
    - pymdownx.highlight
    - pymdownx.superfences
    
nav:
    - Introduction: index.md
    - Installation: install.md
    - API docs: 'http://api.getcohorts.com'    
    - Reference: reference.md
