# Build and test the project, and deploy the docs site and PyPI on new 
# releases. The deploy jobs could be sped up by caching the installed
# packages, but they're fast enough for now.

name: CI

on: [push, release]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2.0.0
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        pip install .
    - name: Run webserver
      run: gunicorn --bind 0.0.0.0:$PORT -w 2 -k uvicorn.workers.UvicornWorker --daemon getcohorts.web:app
    - name: Test
      run: |
        coverage run -m pytest
        cat coverage.xml
        CODECOV_TOKEN="${{secrets.CODECOV_TOKEN}}" bash <(curl -s https://codecov.io/bash)
  
  # TODO: 
  # 1. Tests for the running web container we can run separately from the rest of the test suite
  # 2. github container registry login and publishing on release
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2.0.0
      with:
        python-version: '3.7'
    - name: Install GetCohorts
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        pip install .
    - name: Build image
      run: |
        docker build . \
          --file Dockerfile \
          --tag getcohorts:$(python -c "import getcohorts; print(getcohorts.__version__);") \
          --tag getcohorts:latest
    - name: Run image
      run: docker run --detach --publish 8000:8000 getcohorts
    - name: Test image
      run: pytest tests/test_api.py

  deploy-docs:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install .    
      - name: Build
        run: |
          mkdocs build
      - name: Deploy Docs
        if: ${{ github.event_name == 'release' }}
        run: |
          AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} aws s3 cp --recursive ./site ${{ secrets.DOCS_S3_BUCKET }}
  
  deploy-pypi:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install .
      - name: Build
        run: |
          python setup.py sdist bdist_wheel && ls dist
      - name: Deploy PyPI
        if: ${{ github.event_name == 'release' }}
        run: |
          twine upload \
            --skip-existing \
            --repository ${{ secrets.PYPI_REPOSITORY }}  \
            --username ${{ secrets.PYPI_USERNAME }} \
            --password ${{ secrets.PYPI_ACCESS_TOKEN }} \
            dist/*
